/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2' | 'h3' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    linkType?: 'href' | 'page'
    href?: string
    page?: PageReference
    openInNewTab?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page'
        href?: string
        page?: PageReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type CbWysiwyg = {
  _type: 'cbWysiwyg'
  content?: BlockContentTextOnly
}

export type CbVideo = {
  _type: 'cbVideo'
  src?: string
  poster?: string
  caption?: string
  autoplay?: boolean
  loop?: boolean
  muted?: boolean
  controls?: boolean
  playsInline?: boolean
}

export type CbSiteLogo = {
  _type: 'cbSiteLogo'
  width?: 'sm' | 'md' | 'lg'
  isLink?: boolean
  linkTarget?: '_self' | '_blank'
}

export type CbShortcode = {
  _type: 'cbShortcode'
  text?: string
}

export type CbParagraph = {
  _type: 'cbParagraph'
  content?: string
  dropCap?: boolean
  textAlign?: 'left' | 'center' | 'right'
  placeholder?: string
  fontSize?: 'sm' | 'md' | 'lg' | 'xl'
}

export type CbNavigation = {
  _type: 'cbNavigation'
  overlayMenu?: 'never' | 'mobile' | 'always'
  openSubmenusOnClick?: boolean
  showSubmenuIcon?: boolean
  icon?: 'menu' | 'dots'
  layout?: 'horizontal' | 'vertical'
  links?: Array<
    {
      _key: string
    } & CbNavigationLink
  >
}

export type CbNavigationLink = {
  _type: 'cbNavigationLink'
  label?: string
  url?: string
  opensInNewTab?: boolean
  description?: string
  type?: 'custom' | 'page'
  link?: CbLink
}

export type PageHeaderAppearance = {
  _type: 'pageHeaderAppearance'
  variant: 'positive' | 'negative'
}

export type PageFooterAppearance = {
  _type: 'pageFooterAppearance'
  variant: 'positive' | 'negative'
}

export type HomeSectorsSection = {
  _type: 'homeSectorsSection'
  contents: Array<
    {
      _key: string
    } & CbColumns
  >
}

export type HomeSectorListItem = {
  _type: 'homeSectorListItem'
  title: string
  link?: CbLink
  isHighlighted?: boolean
}

export type HomeSectorListBlock = {
  _type: 'homeSectorListBlock'
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  items: Array<
    {
      _key: string
    } & HomeSectorListItem
  >
}

export type HomeSectorItem = {
  _type: 'homeSectorItem'
  title: string
  ctaLabel?: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  link: CbLink
}

export type HomeHeroSection = {
  _type: 'homeHeroSection'
  backgroundMedia?: CbMedia
  phrases: Array<
    {
      _key: string
    } & HomeHeroPhrase
  >
  contents: Array<
    {
      _key: string
    } & CbColumns
  >
  floatingActionLabel?: string
  floatingActionLink?: CbLink
}

export type HomeHeroPhrase = {
  _type: 'homeHeroPhrase'
  text: string
  placement: 'upperLeft' | 'middleRight' | 'lowerLeft'
}

export type HomeCompanyItem = {
  _type: 'homeCompanyItem'
  name: string
  category: string
  link?: CbLink
}

export type HomeCompaniesSection = {
  _type: 'homeCompaniesSection'
  backgroundImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  contents: Array<
    {
      _key: string
    } & CbColumns
  >
}

export type HomeCompanyItemsBlock = {
  _type: 'homeCompanyItemsBlock'
  items: Array<
    {
      _key: string
    } & HomeCompanyItem
  >
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type HomeBlogPostsSection = {
  _type: 'homeBlogPostsSection'
  contents?: Array<
    {
      _key: string
    } & CbColumns
  >
  posts: Array<
    {
      _key: string
    } & PostReference
  >
  floatingActionLabel?: string
  floatingActionLink?: CbLink
}

export type HomeAboutSection = {
  _type: 'homeAboutSection'
  contents: Array<
    {
      _key: string
    } & CbColumns
  >
}

export type HomeAboutStatsBlock = {
  _type: 'homeAboutStatsBlock'
  stats: Array<
    {
      _key: string
    } & HomeAboutStat
  >
}

export type HomeAboutStat = {
  _type: 'homeAboutStat'
  value: string
  label: string
  tone: 'dark' | 'blue' | 'outlineDark'
  height: 'sm' | 'md' | 'lg'
}

export type HomeAboutImageBlock = {
  _type: 'homeAboutImageBlock'
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type MenuSubLink = {
  _type: 'menuSubLink'
  itemId: string
  label: string
  link: CbLink
}

export type MenuMegaMenuGroup = {
  _type: 'menuMegaMenuGroup'
  title: string
  columns: Array<
    {
      _key: string
    } & MenuMegaMenuColumn
  >
}

export type MenuMegaMenuColumn = {
  _type: 'menuMegaMenuColumn'
  links: Array<
    {
      _key: string
    } & MenuSubLink
  >
}

export type MenuMegaMenu = {
  _type: 'menuMegaMenu'
  groups: Array<
    {
      _key: string
    } & MenuMegaMenuGroup
  >
}

export type MenuLink = {
  _type: 'menuLink'
  itemId: string
  label: string
  link: CbLink
  subLinks?: Array<
    {
      _key: string
    } & MenuSubLink
  >
  megaMenu?: MenuMegaMenu
}

export type MenuGroup = {
  _type: 'menuGroup'
  menuId: string
  title?: string
  links: Array<
    {
      _key: string
    } & MenuLink
  >
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type CbMedia = {
  _type: 'cbMedia'
  mediaType: 'image' | 'video'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  videoFile?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type CbList = {
  _type: 'cbList'
  ordered?: boolean
  start?: number
  reversed?: boolean
  items?: Array<
    {
      _key: string
    } & CbListItem
  >
  values?: Array<string>
}

export type CbListItem = {
  _type: 'cbListItem'
  content?: string
}

export type CbLink = {
  _type: 'cbLink'
  linkType?: 'external' | 'internal'
  externalUrl?: string
  internalTargetType?: 'page' | 'path'
  internalPage?: PageReference
  internalPath?: string
  openInNewTab?: boolean
}

export type CbImage = {
  _type: 'cbImage'
  media?: CbMedia
  url?: string
  alt?: string
  caption?: string
  href?: string
  linkTarget?: '_self' | '_blank'
  aspectRatio?: 'auto' | '1/1' | '4/3' | '16/9' | '3/4' | '9/16'
  scale?: 'cover' | 'contain'
  sizeSlug?: string
}

export type CbHtml = {
  _type: 'cbHtml'
  content?: string
}

export type CbHeading = {
  _type: 'cbHeading'
  content?: string
  level?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  textAlign?: 'left' | 'center' | 'right'
  placeholder?: string
}

export type CbGroup = {
  _type: 'cbGroup'
  tagName?: 'div' | 'section' | 'article' | 'aside' | 'header' | 'footer' | 'main'
  layout?: 'default' | 'constrained' | 'flex' | 'grid'
  align?: 'left' | 'center' | 'right' | 'wide' | 'full'
  contents: Array<
    | ({
        _key: string
      } & CbBlock)
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbShortcode)
    | ({
        _key: string
      } & CbSiteLogo)
    | ({
        _key: string
      } & CbVideo)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & HomeAboutImageBlock)
    | ({
        _key: string
      } & HomeAboutStatsBlock)
    | ({
        _key: string
      } & HomeCompanyItemsBlock)
    | ({
        _key: string
      } & HomeSectorItem)
    | ({
        _key: string
      } & HomeSectorListBlock)
  >
  children?: Array<
    | ({
        _key: string
      } & CbBlock)
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbShortcode)
    | ({
        _key: string
      } & CbSiteLogo)
    | ({
        _key: string
      } & CbVideo)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & HomeAboutImageBlock)
    | ({
        _key: string
      } & HomeAboutStatsBlock)
    | ({
        _key: string
      } & HomeCompanyItemsBlock)
    | ({
        _key: string
      } & HomeSectorItem)
    | ({
        _key: string
      } & HomeSectorListBlock)
  >
}

export type CbCover = {
  _type: 'cbCover'
  backgroundMedia?: CbMedia
  url?: string
  backgroundType?: 'image' | 'video'
  alt?: string
  dimRatio?: number
  overlayColor?: string
  contentPosition?:
    | 'top-left'
    | 'top-center'
    | 'top-right'
    | 'center-left'
    | 'center-center'
    | 'center-right'
    | 'bottom-left'
    | 'bottom-center'
    | 'bottom-right'
  minHeight?: 'sm' | 'md' | 'lg' | 'full'
  hasParallax?: boolean
  contents: Array<
    | ({
        _key: string
      } & CbBlock)
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbShortcode)
    | ({
        _key: string
      } & CbSiteLogo)
    | ({
        _key: string
      } & CbVideo)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & HomeAboutImageBlock)
    | ({
        _key: string
      } & HomeAboutStatsBlock)
    | ({
        _key: string
      } & HomeCompanyItemsBlock)
    | ({
        _key: string
      } & HomeSectorItem)
    | ({
        _key: string
      } & HomeSectorListBlock)
  >
  content?: Array<
    | ({
        _key: string
      } & CbBlock)
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbShortcode)
    | ({
        _key: string
      } & CbSiteLogo)
    | ({
        _key: string
      } & CbVideo)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & HomeAboutImageBlock)
    | ({
        _key: string
      } & HomeAboutStatsBlock)
    | ({
        _key: string
      } & HomeCompanyItemsBlock)
    | ({
        _key: string
      } & HomeSectorItem)
    | ({
        _key: string
      } & HomeSectorListBlock)
  >
}

export type CbColumns = {
  _type: 'cbColumns'
  isStackedOnMobile?: boolean
  verticalAlignment?: 'top' | 'center' | 'bottom'
  gap?: 'none' | 'sm' | 'md' | 'lg'
  columns: Array<
    {
      _key: string
    } & CbColumn
  >
}

export type CbColumn = {
  _type: 'cbColumn'
  width?: 'auto' | '1/2' | '1/3' | '1/4' | '2/3' | '3/4'
  verticalAlignment?: 'top' | 'center' | 'bottom'
  contents: Array<
    | ({
        _key: string
      } & CbBlock)
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbShortcode)
    | ({
        _key: string
      } & CbSiteLogo)
    | ({
        _key: string
      } & CbVideo)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & HomeAboutImageBlock)
    | ({
        _key: string
      } & HomeAboutStatsBlock)
    | ({
        _key: string
      } & HomeCompanyItemsBlock)
    | ({
        _key: string
      } & HomeSectorItem)
    | ({
        _key: string
      } & HomeSectorListBlock)
  >
  children?: Array<
    | ({
        _key: string
      } & CbBlock)
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbShortcode)
    | ({
        _key: string
      } & CbSiteLogo)
    | ({
        _key: string
      } & CbVideo)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & HomeAboutImageBlock)
    | ({
        _key: string
      } & HomeAboutStatsBlock)
    | ({
        _key: string
      } & HomeCompanyItemsBlock)
    | ({
        _key: string
      } & HomeSectorItem)
    | ({
        _key: string
      } & HomeSectorListBlock)
  >
}

export type CbButtons = {
  _type: 'cbButtons'
  align?: 'left' | 'center' | 'right'
  orientation?: 'horizontal' | 'vertical'
  items: Array<
    {
      _key: string
    } & CbButton
  >
}

export type CbButton = {
  _type: 'cbButton'
  text?: string
  url?: string
  linkTarget?: '_self' | '_blank'
  size?: 'sm' | 'md' | 'lg'
  variant?: 'primary' | 'secondary' | 'ghost'
  label?: string
  actionType: 'button' | 'link'
  link?: CbLink
}

export type CbBlock = {
  _type: 'cbBlock'
  ref: string
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  language: string
  publishedAt: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  headerAppearance?: PageHeaderAppearance
  footerAppearance?: PageFooterAppearance
  pageBuilder?: Array<
    {
      _key: string
    } & CbColumns
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    canonicalUrl?: string
    noIndex?: boolean
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }
  structuredData?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  positiveLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  negativeLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  navigationGroups?: Array<
    {
      _key: string
    } & MenuMegaMenuGroup
  >
  heading?: string
  legalMenu?: MenuGroup
  showDefaultLegalLinks?: boolean
  copyrightText?: string
  creditLabel?: string
  creditLink?: CbLink
}

export type Header = {
  _id: string
  _type: 'header'
  _createdAt: string
  _updatedAt: string
  _rev: string
  positiveLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  negativeLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  primaryMenu: MenuGroup
  secondaryMenu: MenuGroup
  ctaLabel?: string
  ctaLink?: CbLink
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page'
      href?: string
      page?: PageReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  companyName?: string
  officeLocations?: Array<{
    title?: string
    address: string
    _key: string
  }>
  contactPhone?: string
  contactEmail?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  gtmScript?: string
  gaScript?: string
  cookiePolicyScript?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type LegalPageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'legalPage'
}

export type HomePageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'homePage'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?: PageReference | LegalPageReference | HomePageReference
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  language: string
  headerAppearance?: PageHeaderAppearance
  footerAppearance?: PageFooterAppearance
  pageBuilder?: Array<
    | ({
        _key: string
      } & HomeHeroSection)
    | ({
        _key: string
      } & HomeAboutSection)
    | ({
        _key: string
      } & HomeSectorsSection)
    | ({
        _key: string
      } & HomeCompaniesSection)
    | ({
        _key: string
      } & HomeBlogPostsSection)
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    canonicalUrl?: string
    noIndex?: boolean
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }
  structuredData?: string
}

export type LegalPage = {
  _id: string
  _type: 'legalPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: 'privacy-policy' | 'terms-and-conditions'
  language: string
  headerAppearance?: PageHeaderAppearance
  footerAppearance?: PageFooterAppearance
  content: BlockContent
  structuredData?: string
  seo?: {
    metaDescription?: string
    canonicalUrl?: string
    noIndex?: boolean
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  language: string
  headerAppearance?: PageHeaderAppearance
  footerAppearance?: PageFooterAppearance
  pageBuilder?: Array<
    {
      _key: string
    } & CbColumns
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    canonicalUrl?: string
    noIndex?: boolean
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }
  structuredData?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PageReference
  | BlockContentTextOnly
  | SanityImageAssetReference
  | BlockContent
  | CbWysiwyg
  | CbVideo
  | CbSiteLogo
  | CbShortcode
  | CbParagraph
  | CbNavigation
  | CbNavigationLink
  | PageHeaderAppearance
  | PageFooterAppearance
  | HomeSectorsSection
  | HomeSectorListItem
  | HomeSectorListBlock
  | HomeSectorItem
  | HomeHeroSection
  | HomeHeroPhrase
  | HomeCompanyItem
  | HomeCompaniesSection
  | HomeCompanyItemsBlock
  | PostReference
  | HomeBlogPostsSection
  | HomeAboutSection
  | HomeAboutStatsBlock
  | HomeAboutStat
  | HomeAboutImageBlock
  | MenuSubLink
  | MenuMegaMenuGroup
  | MenuMegaMenuColumn
  | MenuMegaMenu
  | MenuLink
  | MenuGroup
  | SanityFileAssetReference
  | CbMedia
  | CbList
  | CbListItem
  | CbLink
  | CbImage
  | CbHtml
  | CbHeading
  | CbGroup
  | CbCover
  | CbColumns
  | CbColumn
  | CbButtons
  | CbButton
  | CbBlock
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Footer
  | Header
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | TranslationMetadata
  | InternationalizedArrayReference
  | LegalPageReference
  | HomePageReference
  | InternationalizedArrayReferenceValue
  | HomePage
  | LegalPage
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
